[Atualização] - Novo Padrão
betrybe/sd-0x-project-frontend-online-store-rubric pull request #3
Opened 2021-03-31 14:50 UTC by LucasSGomide

2021-05-13 15:09 UTC, JefersonSchimuneck approved these changes

2021-05-17 12:03 UTC, mhamaji requested changes

2021-05-17 12:03 UTC, mhamaji commented on README.md
> +testes bruno
Tem isso aqui mesmo?

2021-05-18 12:37 UTC, JefersonSchimuneck commented on README.md
> +testes bruno
Apaguei a linha.

2021-05-19 12:18 UTC, JefersonSchimuneck approved these changes

2021-07-16 20:36 UTC, renatofreire approved these changes

2021-07-20 12:42 UTC, merged