[Readme Review] Atualiza README e mocks dos testes do projeto
betrybe/sd-0x-project-frontend-online-store-rubric pull request #6
Opened 2021-07-07 15:14 UTC by vitrokb

Atualiza Readme do projeto e atualiza mock dos fetch nos testes para usar todos os endpoints descritos no Readme.

Issue: https://github.com/betrybe/course/issues/4464

2021-07-07 20:48 UTC, EduardoSantosF reviewed
Ficou muito bom!
Para ficar ainda melhor, eu acredito que seria interessante colocar um caso default no mock, assim caso o url não for encontrado, o retorno do fetch não será undefined.

2021-07-19 21:47 UTC, renatofreire requested changes
Deixei ~um monte~ alguns comentários, mas é basicamente a mesma coisa que se repete em vários arquivos :smile:

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement11.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
:eyes: 
 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement12.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
Mesma situação aqui :dog: 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement13.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
Aqui também :grimacing: 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement13.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
:warning:  Aqui temos uma "pegadinha"

Como temos mais de um `it` dentro do mesmo `describe`, a gente precisa limpar o mock feito para que a contagem dê certo. 

Além do `toHaveBeenCalledTimes(2)` na linha 29, vamos precisar adicionar o seguinte trecho entre o `describe` (linha 6) e o `it` (linha 7):

```javascript
  afterEach(() => {
    global.fetch.mockClear();
  });
```
Dessa forma a gente limpa o mock feita depois de cada teste. Sem o `mockClear`, a contagem de chamadas do `fetch` nesse ponto seria 4 ao invés de 2.

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement14.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
Eu já falei para você sobre o `toHaveBeenCalledTimes(2)`? :rofl: :rofl: 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement15.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
:checkered_flag: :tada: 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement06.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
Nesse caso, se a gente quiser garantir que o `fetch` foi chamado duas vezes, é melhor usar o método `toHaveBeenCalledTimes(2)`.
Como o método `toHaveBeenCalled` verifica que se a função foi chamada 1 ou mais vezes (>=1), aqui nessa linha sempre vai dar `true`, porque o `fetch` já foi chamado uma vez antes.
```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement07.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
Mesma coisa aqui  :) 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement08.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
Aqui também :detective: 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement09.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
Neste teste também :cat: 

```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement10.test.js
> +    await waitFor(() => expect(global.fetch).toHaveBeenCalled());
:man_dancing: 
```suggestion
    await waitFor(() => expect(global.fetch).toHaveBeenCalledTimes(2));
```

2021-07-19 21:47 UTC, renatofreire commented on src/__tests__/requirement01.test.js
>    it('Implementa a função `getCategories`', () => {
Aqui é a mesma situação do comentário do arquivo `requirement13`.
Como a gente tem mais de um `it` no mesmo `describe`, seria legal a gente adicionar o trecho a seguir entre a o `describe` (linha 5) e o `it` (linha 6):
```javascript
  afterEach(() => {
    global.fetch.mockClear();
  });
``` 

Dessa forma a gente evita que o mock de um teste interfira nos outros testes.

2021-07-21 12:52 UTC, vitrokb commented
> Deixei ~um monte~ alguns comentários, mas é basicamente a mesma coisa que se repete em vários arquivos

opa, sem problemas, a parte do toHaveBeenCalledTimes() passou despercebido!

2021-07-25 21:48 UTC, renatofreire approved these changes

2021-07-27 15:01 UTC, JefersonSchimuneck approved these changes

2021-07-27 15:07 UTC, JefersonSchimuneck reviewed
.

2021-07-27 15:08 UTC, JefersonSchimuneck requested changes
Fala @vitrokb !

Este projeto é de rubrica, mas não tem nenhum requisito passando, consegue verificar? Valeu!

2021-08-02 14:26 UTC, JefersonSchimuneck commented
@vitrokb Vitor, estes dias houve um merge nesta branch que já tem o gabarito, acho que está ok este caso. https://github.com/betrybe/sd-0x-project-frontend-online-store-rubric/pull/3

2021-08-17 11:30 UTC, JefersonSchimuneck approved these changes

2021-08-17 11:43 UTC, merged